// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:061f7b4b-149c-4c39-a4af-3c705875d4d6',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'marketchart-hosting-mobilehub-572664129',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3k64h9tkkondf.cloudfront.net',
    'aws_mobile_analytics_app_id': '070c6df1fbd546ea910fef6281ff4577',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '22437a9f-3e42-4e7a-be63-25a26a5ea596',
    'aws_project_name': 'Market_Chart_2018',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'marketchart-mobilehub-572664129',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_dfJyCDtRY',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7mkgr1hivpkhufs6pni6m74ciu',
}

export default awsmobile;
