// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:9affe4c8-19d1-4b67-83c5-d1533c7d6d08',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'marketchart-hosting-mobilehub-390293402',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2rttk65fky308.cloudfront.net',
    'aws_mobile_analytics_app_id': '783e08a40d104d0385e59630e30b128c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a0774cb4-076e-47e0-b069-571f8ddbe6e6',
    'aws_project_name': 'Market-Chart-1',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'marketchart-mobilehub-390293402',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'marketchart-userfiles-mobilehub-390293402',
    'aws_user_files_s3_bucket_region': 'us-east-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_BRX5PPUYe',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1m5t385ppopoqt8v3s4o816hfa',
}

export default awsmobile;
