// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:6abf2329-f9fe-4014-97a7-c27735e2e935',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'marketchart-hosting-mobilehub-765298913',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'depgshzk2xp2f.cloudfront.net',
    'aws_mobile_analytics_app_id': '248c96362355477eb355a8674bfa1f32',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7cd013bc-31fd-4e91-89c3-719f83aee63d',
    'aws_project_name': 'Market Chart',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'marketchart-mobilehub-765298913',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_QPXkcxe32',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '37oeqm62ij2n2g5opttuhveunt',
}

export default awsmobile;
